using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using ESFA.DC.PeriodEnd.ReportService.Reports.Interface;
using ESFA.DC.PeriodEnd.ReportService.Reports.Interface.AppsMonthly.Model;
using ESFA.DC.PeriodEnd.ReportService.Reports.Interface.AppsMonthly.Persistence;
using ESFA.DC.ReportData.Model;

namespace ESFA.DC.PeriodEnd.ReportService.Reports.AppsMonthly
{
    public class AppsMonthlyPersistenceMapper : IAppsMonthlyPersistenceMapper
    {
        public IEnumerable<AppsMonthlyPayment> Map(IReportServiceContext reportServiceContext,
            IEnumerable<AppsMonthlyRecord> appsMonthlyRecords, CancellationToken cancellationToken)
        {
            return appsMonthlyRecords.Select(m => new AppsMonthlyPayment
            {
                Ukprn = reportServiceContext.Ukprn,
                ReturnPeriod = reportServiceContext.ReturnPeriod,
                LearnerFamilyName = m.Learner?.FamilyName,
                LearnerGivenNames = m.Learner?.GivenNames,
                PaymentLearnerReferenceNumber = m.RecordKey.LearnerReferenceNumber,
                PaymentUniqueLearnerNumber = m.RecordKey.Uln,
                LearnerCampusIdentifier = m.Learner?.CampusIdentifier,
                ProviderSpecifiedLearnerMonitoringA = m.ProviderMonitorings?.LearnerA,
                ProviderSpecifiedLearnerMonitoringB = m.ProviderMonitorings?.LearnerA,
                PaymentEarningEventAimSeqNumber = m.Earning?.AimSequenceNumber,
                PaymentLearningAimReference = m.RecordKey.LearningAimReference,
                LarsLearningDeliveryLearningAimTitle = m.LearningDeliveryTitle,
                LearningDeliveryOriginalLearningStartDate = m.LearningDelivery?.OrigLearnStartDate,
                PaymentLearningStartDate = m.RecordKey.LearnStartDate,
                LearningDeliveryLearningPlannedEndDate = m.LearningDelivery?.LearnPlanEndDate,
                LearningDeliveryCompletionStatus = m.LearningDelivery?.CompStatus,
                LearningDeliveryLearningActualEndDate = m.LearningDelivery?.LearnActEndDate,
                LearningDeliveryAchievementDate  = m.LearningDelivery?.AchDate,
                LearningDeliveryOutcome = m.LearningDelivery?.Outcome,
                PaymentProgrammeType = m.RecordKey.ProgrammeType,
                PaymentStandardCode = m.RecordKey.StandardCode ,
                PaymentFrameworkCode = m.RecordKey.FrameworkCode,
                PaymentPathwayCode = m.RecordKey.PathwayCode,
                LearningDeliveryAimType = m.LearningDelivery?.AimType,
                LearningDeliverySoftwareSupplierAimIdentifier = m.LearningDelivery?.SWSupAimId,
                LearningDeliveryFamTypeLearningDeliveryMonitoringA = m.LearningDeliveryFams?.LDM1,
                LearningDeliveryFamTypeLearningDeliveryMonitoringB = m.LearningDeliveryFams?.LDM2,
                LearningDeliveryFamTypeLearningDeliveryMonitoringC = m.LearningDeliveryFams?.LDM3,
                LearningDeliveryFamTypeLearningDeliveryMonitoringD = m.LearningDeliveryFams?.LDM4,
                LearningDeliveryFamTypeLearningDeliveryMonitoringE = m.LearningDeliveryFams?.LDM5,
                LearningDeliveryFamTypeLearningDeliveryMonitoringF = m.LearningDeliveryFams?.LDM6,
                ProviderSpecifiedDeliveryMonitoringA = m.ProviderMonitorings?.LearningDeliveryA,
                ProviderSpecifiedDeliveryMonitoringB = m.ProviderMonitorings?.LearningDeliveryB,
                ProviderSpecifiedDeliveryMonitoringC = m.ProviderMonitorings?.LearningDeliveryC,
                ProviderSpecifiedDeliveryMonitoringD = m.ProviderMonitorings?.LearningDeliveryD,
                LearningDeliveryEndPointAssessmentOrganisation = m.LearningDelivery?.EPAOrgId,
                RulebaseAecLearningDeliveryPlannedNumberOfOnProgrammeInstalmentsForAim = m.LearningDelivery?.AecLearningDelivery?.PlannedNumOnProgInstalm,
                LearningDeliverySubContractedOrPartnershipUkprn = m.LearningDelivery?.PartnerUkprn,
                PaymentPriceEpisodeStartDate = m.PriceEpisodeStartDate,
                RulebaseAecApprenticeshipPriceEpisodePriceEpisodeActualEndDate = m.PriceEpisode?.PriceEpisodeActualEndDateIncEPA,
                FcsContractContractAllocationContractAllocationNumber = m.ContractNumber,
                PaymentFundingLineType = m.RecordKey.ReportingAimFundingLineType,
                PaymentApprenticeshipContractType = m.RecordKey.ContractType,
                LearnerEmploymentStatusEmployerId = m.LearnerEmploymentStatus?.EmpId,
                LearnerEmploymentStatus = m.LearnerEmploymentStatus?.EmpStat,
                LearnerEmploymentStatusDate = m.LearnerEmploymentStatus?.DateEmpStatApp,

                AugustLevyPayments = m.PaymentPeriods.R01.Levy,
                AugustCoInvestmentPayments = m.PaymentPeriods.R01.CoInvestment ,
                AugustCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R01.CoInvestmentDueFromEmployer,
                AugustEmployerAdditionalPayments = m.PaymentPeriods.R01.EmployerAdditional,
                AugustProviderAdditionalPayments = m.PaymentPeriods.R01.ProviderAdditional,
                AugustApprenticeAdditionalPayments = m.PaymentPeriods.R01.ApprenticeAdditional,
                AugustEnglishAndMathsPayments = m.PaymentPeriods.R01.EnglishAndMaths,
                AugustLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R01.LearningSupportDisadvantageAndFrameworkUplifts,
                AugustTotalPayments = m.PaymentPeriods.R01.Total,

                SeptemberLevyPayments = m.PaymentPeriods.R02.Levy,
                SeptemberCoInvestmentPayments = m.PaymentPeriods.R02.CoInvestment,
                SeptemberCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R02.CoInvestmentDueFromEmployer,
                SeptemberEmployerAdditionalPayments = m.PaymentPeriods.R02.EmployerAdditional,
                SeptemberProviderAdditionalPayments = m.PaymentPeriods.R02.ProviderAdditional,
                SeptemberApprenticeAdditionalPayments = m.PaymentPeriods.R02.ApprenticeAdditional,
                SeptemberEnglishAndMathsPayments = m.PaymentPeriods.R02.EnglishAndMaths,
                SeptemberLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R02.LearningSupportDisadvantageAndFrameworkUplifts,
                SeptemberTotalPayments = m.PaymentPeriods.R02.Total,

                OctoberLevyPayments = m.PaymentPeriods.R03.Levy,
                OctoberCoInvestmentPayments = m.PaymentPeriods.R03.CoInvestment,
                OctoberCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R03.CoInvestmentDueFromEmployer,
                OctoberEmployerAdditionalPayments = m.PaymentPeriods.R03.EmployerAdditional,
                OctoberProviderAdditionalPayments = m.PaymentPeriods.R03.ProviderAdditional,
                OctoberApprenticeAdditionalPayments = m.PaymentPeriods.R03.ApprenticeAdditional,
                OctoberEnglishAndMathsPayments = m.PaymentPeriods.R03.EnglishAndMaths,
                OctoberLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R03.LearningSupportDisadvantageAndFrameworkUplifts,
                OctoberTotalPayments = m.PaymentPeriods.R03.Total,

                NovemberLevyPayments = m.PaymentPeriods.R04.Levy,
                NovemberCoInvestmentPayments = m.PaymentPeriods.R04.CoInvestment,
                NovemberCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R04.CoInvestmentDueFromEmployer,
                NovemberEmployerAdditionalPayments = m.PaymentPeriods.R04.EmployerAdditional,
                NovemberProviderAdditionalPayments = m.PaymentPeriods.R04.ProviderAdditional,
                NovemberApprenticeAdditionalPayments = m.PaymentPeriods.R04.ApprenticeAdditional,
                NovemberEnglishAndMathsPayments = m.PaymentPeriods.R04.EnglishAndMaths,
                NovemberLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R04.LearningSupportDisadvantageAndFrameworkUplifts,
                NovemberTotalPayments = m.PaymentPeriods.R04.Total,

                DecemberLevyPayments = m.PaymentPeriods.R05.Levy,
                DecemberCoInvestmentPayments = m.PaymentPeriods.R05.CoInvestment,
                DecemberCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R05.CoInvestmentDueFromEmployer,
                DecemberEmployerAdditionalPayments = m.PaymentPeriods.R05.EmployerAdditional,
                DecemberProviderAdditionalPayments = m.PaymentPeriods.R05.ProviderAdditional,
                DecemberApprenticeAdditionalPayments = m.PaymentPeriods.R05.ApprenticeAdditional,
                DecemberEnglishAndMathsPayments = m.PaymentPeriods.R05.EnglishAndMaths,
                DecemberLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R05.LearningSupportDisadvantageAndFrameworkUplifts,
                DecemberTotalPayments = m.PaymentPeriods.R05.Total,

                JanuaryLevyPayments = m.PaymentPeriods.R06.Levy,
                JanuaryCoInvestmentPayments = m.PaymentPeriods.R06.CoInvestment,
                JanuaryCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R06.CoInvestmentDueFromEmployer,
                JanuaryEmployerAdditionalPayments = m.PaymentPeriods.R06.EmployerAdditional,
                JanuaryProviderAdditionalPayments = m.PaymentPeriods.R06.ProviderAdditional,
                JanuaryApprenticeAdditionalPayments = m.PaymentPeriods.R06.ApprenticeAdditional,
                JanuaryEnglishAndMathsPayments = m.PaymentPeriods.R06.EnglishAndMaths,
                JanuaryLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R06.LearningSupportDisadvantageAndFrameworkUplifts,
                JanuaryTotalPayments = m.PaymentPeriods.R06.Total,

                FebruaryLevyPayments = m.PaymentPeriods.R07.Levy,
                FebruaryCoInvestmentPayments = m.PaymentPeriods.R07.CoInvestment,
                FebruaryCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R07.CoInvestmentDueFromEmployer,
                FebruaryEmployerAdditionalPayments = m.PaymentPeriods.R07.EmployerAdditional,
                FebruaryProviderAdditionalPayments = m.PaymentPeriods.R07.ProviderAdditional,
                FebruaryApprenticeAdditionalPayments = m.PaymentPeriods.R07.ApprenticeAdditional,
                FebruaryEnglishAndMathsPayments = m.PaymentPeriods.R07.EnglishAndMaths,
                FebruaryLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R07.LearningSupportDisadvantageAndFrameworkUplifts,
                FebruaryTotalPayments = m.PaymentPeriods.R07.Total,

                MarchLevyPayments = m.PaymentPeriods.R08.Levy,
                MarchCoInvestmentPayments = m.PaymentPeriods.R08.CoInvestment,
                MarchCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R08.CoInvestmentDueFromEmployer,
                MarchEmployerAdditionalPayments = m.PaymentPeriods.R08.EmployerAdditional,
                MarchProviderAdditionalPayments = m.PaymentPeriods.R08.ProviderAdditional,
                MarchApprenticeAdditionalPayments = m.PaymentPeriods.R08.ApprenticeAdditional,
                MarchEnglishAndMathsPayments = m.PaymentPeriods.R08.EnglishAndMaths,
                MarchLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R08.LearningSupportDisadvantageAndFrameworkUplifts,
                MarchTotalPayments = m.PaymentPeriods.R08.Total,

                AprilLevyPayments = m.PaymentPeriods.R09.Levy,
                AprilCoInvestmentPayments = m.PaymentPeriods.R09.CoInvestment,
                AprilCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R09.CoInvestmentDueFromEmployer,
                AprilEmployerAdditionalPayments = m.PaymentPeriods.R09.EmployerAdditional,
                AprilProviderAdditionalPayments = m.PaymentPeriods.R09.ProviderAdditional,
                AprilApprenticeAdditionalPayments = m.PaymentPeriods.R09.ApprenticeAdditional,
                AprilEnglishAndMathsPayments = m.PaymentPeriods.R09.EnglishAndMaths,
                AprilLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R09.LearningSupportDisadvantageAndFrameworkUplifts,
                AprilTotalPayments = m.PaymentPeriods.R09.Total,

                MayLevyPayments = m.PaymentPeriods.R10.Levy,
                MayCoInvestmentPayments = m.PaymentPeriods.R10.CoInvestment,
                MayCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R10.CoInvestmentDueFromEmployer,
                MayEmployerAdditionalPayments = m.PaymentPeriods.R10.EmployerAdditional,
                MayProviderAdditionalPayments = m.PaymentPeriods.R10.ProviderAdditional,
                MayApprenticeAdditionalPayments = m.PaymentPeriods.R10.ApprenticeAdditional,
                MayEnglishAndMathsPayments = m.PaymentPeriods.R10.EnglishAndMaths,
                MayLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R10.LearningSupportDisadvantageAndFrameworkUplifts,
                MayTotalPayments = m.PaymentPeriods.R10.Total,

                JuneLevyPayments = m.PaymentPeriods.R11.Levy,
                JuneCoInvestmentPayments = m.PaymentPeriods.R11.CoInvestment,
                JuneCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R11.CoInvestmentDueFromEmployer,
                JuneEmployerAdditionalPayments = m.PaymentPeriods.R11.EmployerAdditional,
                JuneProviderAdditionalPayments = m.PaymentPeriods.R11.ProviderAdditional,
                JuneApprenticeAdditionalPayments = m.PaymentPeriods.R11.ApprenticeAdditional,
                JuneEnglishAndMathsPayments = m.PaymentPeriods.R11.EnglishAndMaths,
                JuneLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R11.LearningSupportDisadvantageAndFrameworkUplifts,
                JuneTotalPayments = m.PaymentPeriods.R11.Total,

                JulyLevyPayments = m.PaymentPeriods.R12.Levy,
                JulyCoInvestmentPayments = m.PaymentPeriods.R12.CoInvestment,
                JulyCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R12.CoInvestmentDueFromEmployer,
                JulyEmployerAdditionalPayments = m.PaymentPeriods.R12.EmployerAdditional,
                JulyProviderAdditionalPayments = m.PaymentPeriods.R12.ProviderAdditional,
                JulyApprenticeAdditionalPayments = m.PaymentPeriods.R12.ApprenticeAdditional,
                JulyEnglishAndMathsPayments = m.PaymentPeriods.R12.EnglishAndMaths,
                JulyLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R12.LearningSupportDisadvantageAndFrameworkUplifts,
                JulyTotalPayments = m.PaymentPeriods.R12.Total,

                R13LevyPayments = m.PaymentPeriods.R13.Levy,
                R13CoInvestmentPayments = m.PaymentPeriods.R13.CoInvestment,
                R13CoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R13.CoInvestmentDueFromEmployer,
                R13EmployerAdditionalPayments = m.PaymentPeriods.R13.EmployerAdditional,
                R13ProviderAdditionalPayments = m.PaymentPeriods.R13.ProviderAdditional,
                R13ApprenticeAdditionalPayments = m.PaymentPeriods.R13.ApprenticeAdditional,
                R13EnglishAndMathsPayments = m.PaymentPeriods.R13.EnglishAndMaths,
                R13LearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R13.LearningSupportDisadvantageAndFrameworkUplifts,
                R13TotalPayments = m.PaymentPeriods.R13.Total,

                R14LevyPayments = m.PaymentPeriods.R14.Levy,
                R14CoInvestmentPayments = m.PaymentPeriods.R14.CoInvestment,
                R14CoInvestmentDueFromEmployerPayments = m.PaymentPeriods.R14.CoInvestmentDueFromEmployer,
                R14EmployerAdditionalPayments = m.PaymentPeriods.R14.EmployerAdditional,
                R14ProviderAdditionalPayments = m.PaymentPeriods.R14.ProviderAdditional,
                R14ApprenticeAdditionalPayments = m.PaymentPeriods.R14.ApprenticeAdditional,
                R14EnglishAndMathsPayments = m.PaymentPeriods.R14.EnglishAndMaths,
                R14LearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.R14.LearningSupportDisadvantageAndFrameworkUplifts,
                R14TotalPayments = m.PaymentPeriods.R14.Total,

                TotalLevyPayments = m.PaymentPeriods.Total.Levy,
                TotalCoInvestmentPayments = m.PaymentPeriods.Total.CoInvestment,
                TotalCoInvestmentDueFromEmployerPayments = m.PaymentPeriods.Total.CoInvestmentDueFromEmployer,
                TotalEmployerAdditionalPayments = m.PaymentPeriods.Total.EmployerAdditional,
                TotalProviderAdditionalPayments = m.PaymentPeriods.Total.ProviderAdditional,
                TotalApprenticeAdditionalPayments = m.PaymentPeriods.Total.ApprenticeAdditional,
                TotalEnglishAndMathsPayments = m.PaymentPeriods.Total.EnglishAndMaths,
                TotalLearningSupportDisadvantageAndFrameworkUpliftPayments = m.PaymentPeriods.Total.LearningSupportDisadvantageAndFrameworkUplifts,
                TotalPayments = m.PaymentPeriods.Total.Total,

            });

        }
    }
}
